// Auto-generated by make-hero-still.sh
// Do not edit manually.

export const heroStill103Png = "/videos/stills/hero-still-103.png";
export const heroStill103Jpg = "/videos/stills/hero-still-103.jpg";
